# Generated by Django 4.1.7 on 2023-09-22 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_user_dob'),
    ]

    operations = [
        migrations.CreateModel(
            name='bookings',
            fields=[
                ('S_No', models.IntegerField(primary_key=True, serialize=False)),
                ('Username', models.CharField(max_length=100, null=True)),
                ('Source', models.CharField(max_length=100, null=True)),
                ('Destination', models.CharField(max_length=100, null=True)),
                ('Date', models.CharField(max_length=20, null=True)),
                ('Time', models.CharField(max_length=20, null=True)),
            ],
            options={
                'db_table': 'bookings',
            },
        ),
    ]
