# Generated by Django 4.1.7 on 2023-06-13 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('S_No', models.IntegerField(primary_key=True, serialize=False)),
                ('Username', models.CharField(max_length=50)),
                ('Password', models.CharField(max_length=50)),
                ('Email', models.CharField(max_length=50)),
                ('Mobile', models.CharField(max_length=20)),
                ('Role', models.CharField(max_length=20)),
                ('Pass_Hash', models.CharField(max_length=256)),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
