# Generated by Django 4.1.7 on 2023-09-06 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_user_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='DOB',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
