# Generated by Django 4.1.7 on 2023-09-25 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_bookings_pay_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookings',
            name='Pay_Status',
            field=models.IntegerField(default='0'),
        ),
    ]
