# Generated by Django 4.1.7 on 2023-09-25 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_bookings_pay_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='Accept_Status',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='Pay_Status',
            field=models.IntegerField(default=0),
        ),
    ]
