# Generated by Django 4.1.7 on 2023-10-31 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_rename_accept_status_bookings_admin_accept_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='Order_Id',
            field=models.CharField(default='', max_length=50),
        ),
    ]
