# Generated by Django 4.2.7 on 2023-12-11 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_bookings_no_of_persons'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='DOB',
        ),
    ]
