# Generated by Django 4.2.7 on 2023-12-13 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_bookings_completion_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='Refund_Status',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
