# Generated by Django 4.1.7 on 2023-09-05 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_user_email_alter_user_mobile'),
    ]

    operations = [
        migrations.CreateModel(
            name='places',
            fields=[
                ('S_No', models.IntegerField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100, null=True)),
            ],
            options={
                'db_table': 'places',
            },
        ),
    ]
