# Generated by Django 4.1.7 on 2023-09-06 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_places_nearby'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Full_Name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
