# Generated by Django 4.1.7 on 2023-10-25 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_bookings_accept_status_alter_bookings_pay_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookings',
            old_name='Accept_Status',
            new_name='Admin_Accept_Status',
        ),
        migrations.AddField(
            model_name='bookings',
            name='Cust_Accept_Status',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='Date',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='Destination',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='Source',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='Time',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='Username',
            field=models.CharField(max_length=100),
        ),
    ]
