# Generated by Django 4.1.7 on 2023-10-31 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_bookings_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookings',
            name='Order_Id',
            field=models.CharField(max_length=50),
        ),
    ]
