# Generated by Django 4.1.7 on 2023-10-31 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_bookings_journey_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookings',
            name='Journey_Status',
            field=models.CharField(choices=[('Ongoing', 'Ongoing'), ('Cancelled', 'Cancelled'), ('Completed', 'Completed')], max_length=50),
        ),
    ]
