# Generated by Django 4.2.7 on 2023-12-09 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_remove_bookings_cust_accept_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='driver',
            fields=[
                ('S_No', models.IntegerField(primary_key=True, serialize=False)),
                ('Username', models.CharField(max_length=50)),
                ('Status', models.CharField(choices=[('Available', 'Available'), ('On Trip', 'On Trip'), ('Unavailable', 'Unavailable')], default='Available', max_length=50)),
                ('Bus_No', models.CharField(max_length=25, null=True)),
                ('Status_Time', models.DateField(auto_now=True)),
                ('Current_Location', models.CharField(max_length=50, null=True)),
            ],
            options={
                'db_table': 'driver',
            },
        ),
        migrations.AddField(
            model_name='bookings',
            name='Bus_No',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='bookings',
            name='Code',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='bookings',
            name='Verify_Status',
            field=models.CharField(choices=[('Verified', 'Verified'), ('Not_Verified', 'Not_Verified')], default='Not_Verified', max_length=50),
        ),
    ]
