# Generated by Django 4.2.7 on 2023-12-11 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_driver_bookings_bus_no_bookings_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='No_Of_Persons',
            field=models.IntegerField(default=0),
        ),
    ]
