# Generated by Django 4.2.7 on 2023-12-12 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_remove_user_dob'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='Allocated_Persons',
            field=models.IntegerField(default=0),
        ),
    ]
