# Generated by Django 4.2.7 on 2023-12-13 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_bookings_allocated_persons'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='Available_Seats',
            field=models.IntegerField(default=12),
        ),
    ]
