# Generated by Django 4.2.7 on 2023-12-13 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_driver_available_seats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookings',
            name='Verify_Status',
            field=models.CharField(choices=[('Verified', 'Verified'), ('Not_Verified', 'Not_Verified')], max_length=50, null=True),
        ),
    ]
