# Generated by Django 4.2.7 on 2023-12-13 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_alter_bookings_verify_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='Completion_Status',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='Verify_Status',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
